### ISSUE TITLE
I can't compile project64 using the settings provided.

### ISSUE THREAD

**Issue by steampunko** [project64/project64-wiki#1]
Whenever I try, I get the following error:
'MSBuild.exe'  is not recognized as an internal or external command, operable program or batch file.

**Comment by project64** [comment]
how are you trying to build?

What version of Visual studio are you using?

**Comment by steampunko** [comment]
Visual Studio 2015 and I'm trying to run it via command line.

Also, I've also tried running it by specifying the location of MSBuild.exe. 

"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe" Project64.sln /p:Platform=x64 /p:Configuration=Release /p:PlatformToolset=v140

and then I get this error

MSBUILD : error MSB1009: Project file does not exist.
Switch: Project64.sln

**Comment by steampunko** [comment]
I'm wanting to compile this version because I've heard some very and I mean _VERY_ bad things about the installer.

**Comment by project64** [comment]
if you open solution does it build inside Visual Studio?

the installer is fine, there is nothing wrong with the installer now

**Comment by steampunko** [comment]
Open solution?

**Comment by project64** [comment]
Open Project64.sln and go build compile all

**Comment by steampunko** [comment]
How do I open visual studio?
I'm not too great at these things

**Comment by project64** [comment]
just double click on Project64.sln

**Comment by steampunko** [comment]
This pops up when I do that
![snipp](https://cloud.githubusercontent.com/assets/16859299/20549140/aec97090-b0de-11e6-9fb0-5ebc05939133.PNG)

I do have Visual Studio installed.

**Comment by project64** [comment]
Are you sure you got visual studio installed?

**Comment by steampunko** [comment]
Yes, I'm sure. I have all of the necessary versions

**Comment by project64** [comment]
open visual studio and go to menu and File -> Open -> Project/Solution and browser for and select "Project64.sln"

**Comment by steampunko** [comment]
I can't currently open visual studio so I'm reinstalling VS to see if that allows me to

**Comment by steampunko** [comment]
~~Alright, I've opened it in Visual Studio but it's throwing out alot of errors~~

~~Nevermind, I just restarted my computer and it opened fine without errors.
So what do I do now?~~

I read what you've already stated and I've built it but now how do I run it?

**Comment by project64** [comment]
select project64 as the default project and select run

**Comment by steampunko** [comment]
How would I do so?

**Comment by DerekTurtleRoe** [comment]
@project64 @steampunko Could we move this to the Project64 issues, and close this one? This is for the Wiki, not the main application...

**Comment by steampunko** [comment]
I put it in here because of the directions on building it didn't work, but I guess I could.
I've pretty much given up on compiling it though due to work on compiling other projects I've found interest in

**Comment by DerekTurtleRoe** [comment]
@steampunko Oh, I see. That actually does make sense, I suppose.

Well, you can also just download nightly builds here:

https://www.pj64-emu.com/nightly-builds

**Comment by Monoverde888** [comment]
could someone close this
